nome=str(input('Digite seu nome completo:')).strip()
nome2=nome.split()
print('Muito prazer em te conhecer,{}.'.format(nome2[0].title()))
print('Seu primeiro nome é {}'.format(nome2[0].title()))
print('Seu último nome é {}'.format(nome2[len(nome2)-1].title()))
